sudo: false

branches:
    only:
    - master
    - develop

language:
    - node_js

node_js:
    - '8.0'

git:
    submodules: false

before_install:
    - git config --global user.name "XWP (bot)"
    - git config --global user.email "tech@xwp.co"
    - git config --global push.default simple
    - git remote set-url origin https://$GITHUB_OAUTH_TOKEN@github.com/xwp/fe-dev-lib.git
    - git checkout $TRAVIS_BRANCH

install:
    - yarn add shelljs babel-core babel-cli

script:
    - yarn run build:commit
